import { readFile } from "node:fs/promises"
import { join } from "node:path"
import { fileURLToPath } from "node:url"
import { describe, expect, test } from "vitest"

const ROOT = fileURLToPath(new URL("../../../", import.meta.url))
const DEPRECATED_IDENTITY_COPY = new RegExp(
  [
    "not a Grok " + "plugin",
    "not a Grok " + "plugin/runtime",
    "setup helper/adapter " + "package only",
  ].join("|"),
)

describe("docs/grok-adapter-parity.md (plan task 1 + T5 contract)", () => {
  test("parity table has at least 10 capability rows", async () => {
    const text = await readFile(join(ROOT, "docs/grok-adapter-parity.md"), "utf8")
    const rows = text.split("\n").filter((line) => line.startsWith("|") && !line.includes("---") && !line.includes("omo-codex capability"))
    expect(rows.length).toBeGreaterThanOrEqual(10)
    expect(text).toContain("src/grok/")
    expect(text).toContain("GrokBuild port")
    expect(text).toContain("Grok Build plugin payload")
    expect(text).toContain("lfgIsPlugin: false")
    expect(text).toContain("not reported as a Grok plugin object")
    expect(text).toContain("setup --run")
    expect(text).toContain("~/.grok/plugins/lfg")
    expect(text).not.toMatch(DEPRECATED_IDENTITY_COPY)
    expect(text).toContain("grok-install/doctor.ts")
    expect(text).toContain("publishGap")
    expect(text).toContain("#22")
    expect(text).toContain("publish-owner-checklist")
    expect(text).toContain("plugin-cache-install.acceptance.test.ts")
    expect(text).toContain("#27")
    expect(text).toMatch(/\| Plugin cache install \|.*\| Implemented/)
    expect(text).toMatch(/\| Install version stamp \|.*\| Implemented/)
    expect(text).toContain("doctor-json-contract.test.ts")
    expect(text).toContain("#31")
    expect(text).toContain("hook-trust.acceptance.test.ts")
    expect(text).toContain("#28")
    expect(text).toContain("config-single-writer.acceptance.test.ts")
    expect(text).toMatch(/\| `config\.toml` merge \|.*\| Implemented/)
    expect(text).toContain("agent-tomls.acceptance.test.ts")
    expect(text).toContain("#30")
    expect(text).toContain("agent-overrides.test.ts")
    expect(text).toMatch(/\| Agent TOML \+ preserve reasoning \|.*\| Implemented/)
    expect(text).toMatch(/\| Extension agent overrides \(LFP port\) \|.*\| Implemented/)
    expect(text).toContain("publish-owner-checklist")
    expect(text).toContain("post-install-ported-hooks.test.ts")
    expect(text).toContain("#32")
    expect(text).toMatch(/\| Extension hooks \(LFP port\) \|.*\| Implemented/)
    expect(text).toMatch(/\| OMO skill payload sync \|.*sync-omo-skills-to-grok\.mjs.*\| Implemented/)
    expect(text).toContain("including `ultimate-browsing` with its references/engine/scripts")
    expect(text).toContain(".lfg-omo-skill-sync.json")
    expect(text).toContain("converts OpenAI agent metadata to `agents/grok.yaml`")
    expect(text).toContain("lfg-owned `lfg-doctor`, `lfg-report-bug`, and `lfg-contribute-bug-fix`")
    expect(text).toContain("not a claim that every deferred component runtime or stealth-browser surface is behavior-adapted")
    expect(text).toMatch(/\| `ultimate-browsing` \|.*skills\/ultimate-browsing.*\| Implemented/)
    expect(text).toMatch(/\| ulw-loop \/ start-work skills \|.*project `\.omo` ledger.*\| Implemented/)
    expect(text).toContain("no ledger tail/content")
    expect(text).toContain("malformed `.omo` fails closed")
    expect(text).toContain("registry-bin-publish-gap")
    expect(text).toContain("npm-publish-root-contract.test.ts")
    expect(text).toContain("setup-doctor-parity.test.ts")
    expect(text).toContain("lfg-project-local.test.ts")
    expect(text).toMatch(/\| Hook trust \|.*\| Implemented/)
    expect(text).toMatch(/\| Project-local `\.grok` repair \|.*\| N\/A/)
    expect(text).toContain("publish-gap-evidence-shape.test.ts")
    expect(text).toContain("doctor-pack-layout.acceptance.test.ts")
    expect(text).toContain("#25")
    expect(text).toMatch(/\| Internal verifier \|.*\| Implemented/)
    expect(text).toMatch(/\| `cleanup` \/ `update` \|.*\| N\/A/)
    expect(text).toContain("#34")
    expect(text).toMatch(/\| Model catalog \|.*\| Implemented/)
    expect(text).not.toMatch(/\| Plugin cache install \|.*\| partial/)
  })

  test("T5: forces mention of native Grok hooks, bridge fallback, and Grok-first OMO parity (failing-first contract)", async () => {
    const text = await readFile(join(ROOT, "docs/grok-adapter-parity.md"), "utf8")
    // These will fail until docs updated (verifier false-positive fix); tests pin exact new wording per T5
    expect(text).toContain("native Grok hooks")
    expect(text).toContain("bridge fallback")
    expect(text).toContain("Grok-first OMO parity")
    expect(text).toContain("Scoped Grok-first OMO parity")
    expect(text).toContain("nativeAgentsStatus: \"verified\"")
    expect(text).toContain("postInstallVerify.nativeAgents.status: \"verified\"")
    expect(text).toContain("Install-only")
    expect(text).toContain("does **not** write agent override")
    expect(text).toContain("Full native OMO agent **behavioral** parity is not claimed")
    expect(text).toContain("native Grok hook")
    // Also pin full OMO + hook surfaces for package mapping
    expect(text).toContain("lfg-grok-hook-bridge.mjs")
    expect(text).toContain("hooks/lfg-native-rules.mjs session-start")
    expect(text).toContain("hooks/lfg-native-rules.mjs user-prompt-submit")
    expect(text).toContain("hooks/lfg-native-rules.mjs post-tool-use")
    expect(text).toContain("hooks/lfg-native-rules.mjs post-compact")
    expect(text).toContain("hooks/lfg-native-ultrawork.mjs user-prompt-submit")
    expect(text).toContain("Grok-native lifecycle")
    expect(text).toMatch(/native.*hook|hook.*native|bridge fallback|Grok-first.*OMO|OMO.*parity/i)
  })

  test("distinguishes core install parity from full OMO component parity for issue 36", async () => {
    const text = await readFile(join(ROOT, "docs/grok-adapter-parity.md"), "utf8")
    expect(text).toContain("## Core Install Parity")
    expect(text).toContain("## Current Parity Score")
    expect(text).toContain("two scores")
    expect(text).toContain("adapter-scope 100 is not full-OMO 100")
    expect(text).toContain("Score A")
    expect(text).toContain("GrokBuild adapter scope")
    expect(text).toContain("**100/100**")
    expect(text).toContain("Score B")
    expect(text).toContain("Full OMO host surface")
    expect(text).toContain("**89/100**")
    expect(text).toContain("baseline **88/100** after T2/T4/T5")
    expect(text).toContain("Out of contract")
    expect(text).toContain("omo-senpi")
    expect(text).toContain("~/.senpi")
    expect(text).toContain("codex_app")
    expect(text).toContain("Score A 100 does not imply Score B 100")
    expect(text).toContain("### Score A — GrokBuild adapter scope")
    expect(text).toContain("### Score B — Full OMO host surface")
    expect(text).toContain("Honest formula (gap-fill train T0–T11 historical snapshot → Score B")
    expect(text).toContain("Status promotions Deferred → Grok-adapted/Implemented **during T0–T11**")
    expect(text).toContain("Explicit residual **WAIVE** bookkeeping")
    expect(text).toContain("Not Score B 90–93 from the gap-fill plan alone")
    expect(text).toContain("last audited score snapshot")
    expect(text).toContain("Post-audit status")
    expect(text).toContain("not** assigned ad hoc arithmetic points")
    expect(text).toContain("one formula across all rows")
    expect(text).toContain("T11-score.txt")
    expect(text).toContain("DUAL-SCORE-100-adapter-scope.md")
    expect(text).toContain("#98")
    expect(text).toContain("#99")
    expect(text).toContain("#100")
    expect(text).toContain("#101")
    expect(text).toContain("#102")
    expect(text).toContain("#103")
    expect(text).toContain("#104")
    expect(text).toContain("automatic LSP lifecycle hook reinjection")
    expect(text).toContain("## Full OMO Component Parity")
    expect(text).toContain("`lfg-component-inventory.json`")
    expect(text).toContain("`lazycodex-ai` / OMO `v4.16.3`")
    expect(text).toContain("https://github.com/code-yeongyu/oh-my-openagent/releases/tag/v4.16.3")
    expect(text).toContain("split hook JSON files under `packages/omo-codex/plugin/hooks/`")
    expect(text).toContain("package-level MCP runtimes for")
    expect(text).toContain("scripts/omo-parity-upkeep.mjs")
    expect(text).toContain("unclassified upstream skill, component, or hook-referenced component")
    for (const [component, status] of [
      ["bootstrap", "Deferred"],
      ["auto-update", "Unsupported"],
      ["comment-checker", "Grok-adapted"],
      ["git-bash", "Manifest-only"],
      ["rules", "Grok-adapted"],
      ["lsp", "Grok-adapted"],
      ["ast_grep", "Grok-adapted"],
      ["codegraph", "Grok-adapted"],
      ["grep_app", "Remote URL manifest-only"],
      ["context7", "Remote URL manifest-only"],
      ["ultrawork", "Grok-adapted"],
      ["ulw-loop", "Grok-adapted"],
      ["ulw-plan", "Grok-adapted"],
      ["start-work-continuation", "Deferred"],
      ["plan-mode-interception", "Deferred"],
      ["prompts-core", "Grok-adapted"],
      ["agent-builder", "Grok-adapted"],
      ["delegate-core", "Grok-adapted"],
      ["boulder-state", "Grok-adapted"],
      ["skills-loader-core", "Grok-adapted"],
      ["teammode", "Grok-adapted"],
      ["lazycodex-executor-verify", "Deferred"],
      ["workflow-selector", "Deferred"],
      ["difficulty-tier-workers", "Grok-adapted"],
      ["telemetry", "Unsupported"],
      ["test-support", "Unsupported"],
    ] as const) {
      expect(text).toMatch(new RegExp(`\\| \`${component}\` \\|.*\\| .*\\| .*\\| ${status} \\|`))
    }
    expect(text).toContain("`Implemented`, `Grok-adapted`, `Manifest-only`, `Remote URL manifest-only`, `Unsupported`, or `Deferred`")
    expect(text).toContain("macOS/non-Windows")
    expect(text).toContain("disabled_mcp_servers")
    expect(text).toContain("Windows-unverified")
    expect(text).toContain("codex_app.create_thread")
    expect(text).toContain("`lazycodex-executor`")
    expect(text).toContain("subagent-stop-verifying-lazycodex-executor-evidence.json")
    expect(text).toContain("components/workflow-selector/hooks/hooks.json")
    expect(text).toContain("#5745")
    expect(text).toContain("difficulty-tier-workers")
    expect(text).toContain("lazycodex-worker-")
    expect(text).toContain("LFG_AUTO_WORKFLOW")
    expect(text).toContain("OMO_CODEX_AUTO_WORKFLOW")
    expect(text).toContain("Upstream package test infrastructure remains Unsupported")
    expect(text).toContain("test-only support code outside the Grok runtime payload")
    expect(text).toContain("src/grok/payload/component-inventory.ts")
    expect(text).toContain("`src/core/omo/rules-engine`")
    expect(text).toContain("`src/core/omo/prompts-core`")
    expect(text).toContain("`src/core/omo/agent-builder`")
    expect(text).toContain("`src/core/omo/delegate-core`")
    expect(text).toContain("`src/core/omo/boulder-state`")
    expect(text).toContain("`src/core/omo/skills-loader-core`")
    expect(text).not.toContain("`src/grok/ports/vendor/prompts-core-vendored/`")
    expect(text).not.toContain("`src/grok/ports/vendor/agent-builder-vendored/`")
    expect(text).not.toContain("`src/grok/ports/vendor/delegate-core-vendored/`")
    expect(text).not.toContain("`src/grok/ports/vendor/boulder-state-vendored/`")
    expect(text).not.toContain("`src/grok/ports/vendor/skills-loader-core-vendored/`")
    expect(text).toContain("T2-comment-checker-runtime.txt")
    expect(text).toContain("T4-ast-grep-runtime.txt")
    expect(text).toContain("T5-lsp-runtime.txt")
    expect(text).toContain("T8-lsp-residual.txt")
    expect(text).toContain("T6-tests.txt")
    expect(text).toContain("T7-promote-or-hold.md")
    expect(text).toContain("T7 HOLD Deferred")
    expect(text).toContain("spawn_subagent")
    expect(text).toContain("general-purpose")
    expect(text).toContain("#100")
    expect(text).toContain("hooks/lfg-native-comment-checker.mjs")
    expect(text).toContain("ast_grep_search")
    expect(text).toContain("typescript_diagnostics")
    expect(text).toContain("hook-bridge.integration.test.ts")
    expect(text).toContain("sync-lazycodex-agents-to-grok.ts")
    expect(text).toContain("automatic reinjection CLI is not packaged")
    expect(text).toContain("getStopHookContinuationContext")
    expect(text).toContain("ledger-backed pure helper")
    expect(text).toContain("T5-runtime.txt")
    expect(text).toContain("hook-time `additionalContext` guidance only")
    expect(text).toContain("workflow-selector` (lfg optional historical; upstream removed #5745), `lazycodex-executor-verify`, `start-work-continuation`")
    expect(text).toContain("`difficulty-tier-workers` Grok-adapted")
    expect(text).toContain("external GPT handoff sizing")
    expect(text).toContain("not active Grok implementers")
    expect(text).toContain("Deferred for automatic lifecycle hook reinjection")
    expect(text).toContain("MCP runtime Grok-adapted; automatic PostToolUse/PostCompact reinjection not claimed")
    // refreshed for task 3/6 of orchestration epic
    expect(text).toContain("host dependency class")
    expect(text).toContain("codex_app")
    expect(text).toContain("Stop/SubagentStop hook")
    expect(text).toContain("missing host surface")
    expect(text).toContain("grok-orchestration-plane.md")
    // T9 residual WAIVE pack honesty (issue #102)
    expect(text).toContain("T9 residual WAIVE")
    expect(text).toContain("T9-residuals.txt")
    expect(text).toContain("#102")
    expect(text).toContain("e222452b874eb65d550fafb1d08d3aaf0d20418f")
    expect(text).toContain("lfg-native-workflow-selector.mjs")
    expect(text).toContain("authenticated GrokBuild host receipt")
    expect(text).toContain("policy / no Codex bootstrap from Grok")
    expect(text).toMatch(/\| `workflow-selector` \|.*authenticated GrokBuild host receipt.*\| Deferred \|/)
    expect(text).toMatch(/\| `plan-mode-interception` \|.*host dependency class: missing host surface.*\| Deferred \|/)
    expect(text).toMatch(/\| `bootstrap` \|.*host dependency class: policy \/ no Codex bootstrap from Grok.*\| Deferred \|/)
    expect(text).not.toMatch(/\| `plan-mode-interception` \|.*\| (Implemented|Grok-adapted) \|/)
    expect(text).not.toMatch(/\| `workflow-selector` \|.*\| (Implemented|Grok-adapted) \|/)
    expect(text).not.toMatch(/\| `bootstrap` \|.*\| (Implemented|Grok-adapted) \|/)
    expect(text).toMatch(/\| `teammode` \|.*\| Grok-adapted \|/)
    expect(text).not.toMatch(/\| `lazycodex-executor-verify` \|.*\| (Implemented|Grok-adapted) \|/)
    expect(text).not.toMatch(/\| `start-work-continuation` \|.*\| (Implemented|Grok-adapted) \|/)
  })

  test("ADR revision 2026-07-17 adds Score C — Rust-sidecar scope", async () => {
    const text = await readFile(join(ROOT, "docs/grok-adapter-parity.md"), "utf8")
    expect(text).toContain("### Score C — Rust-sidecar scope (ADR revision 2026-07-17)")
    expect(text).toContain("**Score C** — Rust-sidecar scope = **2/100 at T1**")
    expect(text).toContain("T1 pi-vt behavioral port")
    expect(text).toContain("3 cargo tests prove VT screen rendering")
    expect(text).toContain("**Score A** — GrokBuild adapter scope = 100/100")
    expect(text).toContain("**Score B** — Full OMO host surface = 89/100")
    expect(text).toContain("cargo check -p xai-grok-omo-senpi")
    expect(text).toContain("cargo test -p xai-grok-omo-senpi")
    expect(text).toContain("do NOT replace the lfg adapter's `assert-omo-parity` gate")
  })
})
