import { chmod, mkdir, writeFile } from "node:fs/promises"
import { join } from "node:path"

const LFG_PACKAGE = "@islee23520/lfg"

const LFG_OWNED_FIRST_ARGS = [
  "setup",
  "doctor",
  "set-tier",
  "xai",
  "mcp",
  "claude",
  "handoff",
  "orchestrator",
  "ulw",
  "ulw-loop",
  "help",
  "--help",
  "-h",
  "--json",
  "--run",
  "--force",
  "--refresh",
  "--install-only",
  "--no-tui",
  "--preset",
  "--reasoning-effort",
  "--coding-tool-adapter",
  "--base-url",
  "--openai-base-url",
].join("|")

export function renderGrokBinLfgWrapper(): string {
  return [
    "#!/bin/sh",
    "# Generated by `lfg setup`. lfg is a wrapper on top of grokbuild: lfg-owned",
    "# subcommands/flags run the lfg tool via npx; bare interactive and every other",
    "# invocation forward to the grok binary in ~/.grok/bin.",
    "set -eu",
    "",
    'first_arg=${1:-}',
    "case \"$first_arg\" in",
    `  ${LFG_OWNED_FIRST_ARGS}) exec npx -y ${LFG_PACKAGE} "$@" ;;`,
    "esac",
    "",
    'if [ -x "$HOME/.grok/bin/grok" ]; then',
    '  exec "$HOME/.grok/bin/grok" "$@"',
    "fi",
    'exec grok "$@"',
    "",
  ].join("\n")
}

export async function ensureGrokBinLfgWrapper(home: string): Promise<string> {
  const binDir = join(home, ".grok", "bin")
  const wrapperPath = join(binDir, "lfg")
  await mkdir(binDir, { recursive: true })
  await writeFile(wrapperPath, renderGrokBinLfgWrapper(), "utf8")
  await chmod(wrapperPath, 0o755)
  return wrapperPath
}
